# https://blog.magnusmontin.net/2018/12/11/using-azure-pipelines-to-publish-your-github-project-to-nuget/

trigger:
- master

name: 1.0.$(rev:.r)

pool:
  vmImage: 'windows-latest'
 
variables:
  buildConfiguration: 'release'
  projectName: 'Orleans.Patterns'
 
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: sdk
    version: '3.x'
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core Projects'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test .NET Core Projects'
  inputs:
    command: test
    projects: 'Test.**/*.csproj'
    arguments: --configuration $(buildConfiguration) --no-build --no-restore
  env:
    ENV_EVENT_SOURCING_AZURE_STORAGE: $(ENV_EVENT_SOURCING_AZURE_STORAGE)

- task: DotNetCoreCLI@2
  displayName: 'Pack Main .NET Core Project'
  inputs:
    command: 'pack'
    packagesToPack: '$(projectName)/$(projectName).csproj'
    nobuild: true
    versioningScheme: 'byBuildNumber'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
